# Generated by Django 3.0.5 on 2020-10-17 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTimeJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleTimeJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Npg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainCharater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('health_per_year', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('intelligence_per_year', models.IntegerField(default=10)),
                ('money', models.IntegerField(default=0)),
                ('money_per_year', models.IntegerField(default=0)),
                ('schedule', models.IntegerField(default=0)),
                ('in_school', models.BooleanField(default=False)),
                ('in_middleschool', models.BooleanField(default=False)),
                ('in_highschool', models.BooleanField(default=False)),
                ('in_university', models.BooleanField(default=False)),
                ('in_higheducation', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('buildings', models.ManyToManyField(related_name='propertis', to='character.Houses')),
                ('friends', models.ManyToManyField(related_name='Friends', to='character.Npg')),
                ('full_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='character.FullTimeJobs')),
                ('middle_job', models.ManyToManyField(to='character.MiddleTimeJobs')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Partner', to='character.Npg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(related_name='Vehicles', to='character.Vehicles')),
            ],
        ),
    ]
