# Generated by Django 3.0.5 on 2020-10-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincharater',
            name='buildings',
            field=models.ManyToManyField(blank=True, null=True, related_name='propertis', to='character.Houses'),
        ),
        migrations.AlterField(
            model_name='maincharater',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='Friends', to='character.Npg'),
        ),
        migrations.AlterField(
            model_name='maincharater',
            name='full_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='character.FullTimeJobs'),
        ),
        migrations.AlterField(
            model_name='maincharater',
            name='middle_job',
            field=models.ManyToManyField(blank=True, null=True, to='character.MiddleTimeJobs'),
        ),
        migrations.AlterField(
            model_name='maincharater',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner', to='character.Npg'),
        ),
        migrations.AlterField(
            model_name='maincharater',
            name='vehicles',
            field=models.ManyToManyField(blank=True, null=True, related_name='Vehicles', to='character.Vehicles'),
        ),
    ]
