# Generated by Django 3.0.5 on 2020-10-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20201017_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincharater',
            old_name='user',
            new_name='user_character',
        ),
    ]
